export default [
    'Agent',
    'Monthly Revenue Target',
    'Closed Last Week',
    'Closed This Week',
    'Total Business Closed This Month',
    'Expected to Close This Month',
    'Strong Interest for This Month',
    'Total Forecast for This Month',
    'Potential for Next Month',
    'Total Leads (MTD)',
    'Total Opportunities (MTD)',
    'Arranged Viewings (MTD)',
    'Completed Viewings (MTD)',
    'Deals (MTD)',
    'Leads / Opportunity',
    'Leads / Arranged Viewings',
    'Leads / Completed Viewings',
    'Opportunity / Completed Viewings',
    'Arranged / Completed Viewings',
    'Completed Viewings / Deals',
    'Opportunity / Deals',
    'Leads / Deals'
];